// Self-hosts the UI typefaces. Google splits a family into per-script woff2
// subsets keyed by unicode-range; this pulls every subset the game needs and
// rewrites the CSS to point at local files, so the game carries its own fonts
// and works offline.
import { mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const OUT = join(ROOT, 'public/assets/fonts')
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36'
const WANT = new Set(['thai', 'latin', 'latin-ext'])

const families = process.argv.slice(2)
if (!families.length) { console.error('usage: fetch-fonts.mjs "Mitr:wght@400;600" ...'); process.exit(1) }

mkdirSync(OUT, { recursive: true })
let css = '/* Generated by tools/fetch-fonts.mjs — do not edit by hand. */\n'

for (const spec of families) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(spec).replace(/%3A/g, ':').replace(/%40/g, '@').replace(/%3B/g, ';')}&display=block`
  const sheet = await fetch(url, { headers: { 'User-Agent': UA } }).then(r => r.text())

  // Each block is preceded by a /* subset */ comment naming the script it covers.
  const blocks = sheet.split('/*').slice(1)
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim()
    if (!WANT.has(subset)) continue
    const body = block.slice(block.indexOf('*/') + 2)
    const src = body.match(/url\((https:[^)]+)\)/)?.[1]
    const family = body.match(/font-family:\s*'([^']+)'/)?.[1]
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1] ?? '400'
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]
    if (!src || !family) continue

    const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`
    const bin = Buffer.from(await fetch(src, { headers: { 'User-Agent': UA } }).then(r => r.arrayBuffer()))
    writeFileSync(join(OUT, file), bin)
    css += `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:block;`
      // Relative to this stylesheet, not to the root of a domain. Vite copies
      // whatever is in public/ without touching it, so a root-absolute url here
      // asks for /assets/fonts/... whatever the game is actually served under —
      // and a game served from a path below the root gets no fonts at all, with
      // nothing on screen to say why.
      + `src:url('./${file}') format('woff2');${range ? `unicode-range:${range};` : ''}}\n`
    console.log(`  ${file.padEnd(34)} ${String(bin.length).padStart(7)} bytes`)
  }
}
writeFileSync(join(OUT, 'fonts.css'), css)
console.log(`\nwrote public/assets/fonts/fonts.css`)
